add periodic sync trigger
gardener/oidc-webhook-authenticator pull request #9
Opened 2021-04-26 05:54 UTC by pidah

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```feature user

```

2021-04-28 04:45 UTC, mvladev requested changes

2021-04-28 04:45 UTC, mvladev commented on controllers/authentication/openidconnect_controller.go
> +var ResyncPeriod time.Duration
Don't expose this as global variable - add this to the controller struct and have `AddFlags` and `ApplyTo` functions that can be used to add the flags and apply the value of those flags to the configuration

2021-05-12 05:59 UTC, mvladev commented
Rebase this PR on top of the `master` branch not the upcoming offline issuer branch

2021-05-17 07:57 UTC, mvladev reviewed
With this change, you need to remove the predicate or this won't work as expected

```
WithEventFilter(predicate.GenerationChangedPredicate{}).
```

https://github.com/gardener/oidc-webhook-authenticator/pull/9/files#diff-abfd17e4d40d2b8ddcbad0d9d43f682557f066f9daf7a0761bba03807b357072L169

2021-05-17 09:53 UTC, pidah commented
I can remove, but from my testing, the periodic sync triggers reconciliation when the spec is unchanged and the metadata field is changed.

2021-05-25 06:41 UTC, mvladev approved these changes

2021-05-25 06:42 UTC, merged